from dataclasses import dataclass

import numpy as np
import numpy.typing as npt


@dataclass
class SimulationData:
    iteration: int
    dt: float
    shape: tuple[int, int]
    spacing: [float, float]
    x: npt.NDArray[np.float64]
    y: npt.NDArray[np.float64]
    vx: npt.NDArray[np.float64]
    vy: npt.NDArray[np.float64]

    @property
    def time(self) -> float:
        return self.iteration * self.dt


class Simulation:
    """
    An animated vector field generated by a math expression

    https://shaddenlab.berkeley.edu/uploads/LCS-tutorial/examples.html
    """

    def __init__(self, resolution=(256, 128)):
        self._step = 0
        self._dt = 0.1

        # EQUATION PARAMETERS
        # magnitude of velocity vectors
        self._A = 0.1
        # frequency of oscillation = ω/(2π)
        self._ω = 2.0 * np.pi / 10.0
        # separation motion amplitude
        self._ϵ = 0.25

        # 2D domain
        self._xshape, self._yshape = resolution

        self._xaxis = np.linspace(0.0, 2.0, self._xshape)
        self._yaxis = np.linspace(0.0, 1.0, self._yshape)

        # velocity vector field
        self._u = np.zeros(resolution, dtype=np.float64)
        self._v = np.zeros(resolution, dtype=np.float64)

    def compute_next_step(self):
        # stream equation is
        # ψ = A · sin(πϝ(x,t)) · sin(πy)
        #
        # where:
        #   ϝ(x,t) = a(t) x² + b(t) x
        #   a(t) = ε sin(ωt)
        #   b(t) = 1 - 2 ε sin(ωt)

        t = self._step * self._dt

        # time-dependent and space-invariant coefficients
        a_t = self._ϵ * np.sin(self._ω * t)
        b_t = 1.0 - 2.0 * a_t

        # velocity field
        # vx = - δψ/δy    and     vy = δψ/δx
        for iy, y in enumerate(self._yaxis):
            for ix, x in enumerate(self._xaxis):
                # ϝ(x,t) = a(t) x² + b(t) x
                ϝ_x_t = a_t * x**2 + b_t * x

                # δf/δx
                δϝ_δx = 2 * a_t * x + b_t

                # u = -δψ/δy
                self._u[ix, iy] = (
                    -np.pi * self._A * np.sin(np.pi * ϝ_x_t) * np.cos(np.pi * y)
                )
                # v = δψ/δx
                self._v[ix, iy] = (
                    np.pi * self._A * np.cos(np.pi * ϝ_x_t) * np.sin(np.pi * y) * δϝ_δx
                )

        self._step += 1

    def data(self) -> SimulationData:
        # note that self._u and self._v uses ij indexing with row-major layout
        return SimulationData(
            x=self._xaxis,
            y=self._yaxis,
            vx=self._u,
            vy=self._v,
            shape=(self._xshape, self._yshape),
            spacing=(
                self._xaxis[1] - self._xaxis[0],
                self._yaxis[1] - self._yaxis[0],
            ),  # TODO
            iteration=self._step,
            dt=self._dt,
        )
