from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from tqdm import tqdm


@dataclass
class SimulationData:
    iteration: int
    dt: float
    shape: tuple[int, int]
    spacing: [float, float]
    x: np.array
    y: np.array
    vx: np.ndarray
    vy: np.ndarray

    @property
    def time(self) -> float:
        return self.iteration * self.dt


class Simulation:
    """
    An animated vector field generated by a math expression

    https://shaddenlab.berkeley.edu/uploads/LCS-tutorial/examples.html
    """

    def __init__(self, resolution=(256, 128), iterations=10):
        self._nsteps = iterations
        self._step = 0

        self._dt = 0.1

        # EQUATION PARAMETERS
        # magnitude of velocity vectors
        self._A = 0.1
        # frequency of oscillation = ω/(2π)
        self._ω = 2.0 * np.pi / 10.0
        # separation motion amplitude
        self._ϵ = 0.25

        # 2D domain
        self._xshape, self._yshape = resolution

        self._xaxis = np.linspace(0.0, 2.0, self._xshape)
        self._yaxis = np.linspace(0.0, 1.0, self._yshape)

        # velocity vector field
        self._u = np.zeros(resolution, dtype=np.float64)
        self._v = np.zeros(resolution, dtype=np.float64)

    def _compute_step(self):
        # stream equation is
        # ψ = A · sin(πϝ(x,t)) · sin(πy)
        #
        # where:
        #   ϝ(x,t) = a(t) x² + b(t) x
        #   a(t) = ε sin(ωt)
        #   b(t) = 1 - 2 ε sin(ωt)

        t = self._step * self._dt

        # time-dependent and space-invariant coefficients
        a_t = self._ϵ * np.sin(self._ω * t)
        b_t = 1.0 - 2.0 * a_t

        # velocity field
        # vx = - δψ/δy    and     vy = δψ/δx
        for iy, y in enumerate(self._yaxis):
            for ix, x in enumerate(self._xaxis):
                # ϝ(x,t) = a(t) x² + b(t) x
                ϝ_x_t = a_t * x**2 + b_t * x

                # δf/δx
                δϝ_δx = 2 * a_t * x + b_t

                # u = -δψ/δy
                self._u[ix, iy] = (
                    -np.pi * self._A * np.sin(np.pi * ϝ_x_t) * np.cos(np.pi * y)
                )
                # v = δψ/δx
                self._v[ix, iy] = (
                    np.pi * self._A * np.cos(np.pi * ϝ_x_t) * np.sin(np.pi * y) * δϝ_δx
                )

        self._step += 1

    def data(self) -> SimulationData:
        # note that self._u and self._v uses ij indexing with row-major layout
        return SimulationData(
            x=self._xaxis,
            y=self._yaxis,
            vx=self._u,
            vy=self._v,
            shape=(self._xshape, self._yshape),
            spacing=(
                self._xaxis[1] - self._xaxis[0],
                self._yaxis[1] - self._yaxis[0],
            ),  # TODO
            iteration=self._step,
            dt=self._dt,
        )

    def run(self, callback: Callable[[SimulationData], None] | None = None) -> None:
        with tqdm(total=self._nsteps) as progress_bar:
            while self._step < self._nsteps:
                self._compute_step()

                if callback:
                    callback(self.data())

                progress_bar.update()


def make_visualization_adaptor_from(args):
    from contextlib import nullcontext

    match args.command:
        case "matplotlib":
            from adaptors.matplotlib import draw_matplotlib

            return nullcontext(), draw_matplotlib
        case "insitu":
            from adaptors.catalyst import CatalystAdaptor

            adaptor = CatalystAdaptor(
                config_filepath=args.config, coordtype=args.mesh_type
            )
            return adaptor, adaptor.callback
        case _:
            return nullcontext(), None


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Doubly Gyre Simulation")
    parser.add_argument(
        "-t",
        "--timesteps",
        type=int,
        help="number of timesteps to run the miniapp",
        default=250,
    )

    parser_sub = parser.add_subparsers(dest="command")

    cmd_matplotlib = parser_sub.add_parser("matplotlib")

    cmd_insitu = parser_sub.add_parser("insitu")
    cmd_insitu.add_argument("--config", type=str, default=None)
    cmd_insitu.add_argument("--mesh-type", type=str, default="uniform")

    args = parser.parse_args()

    adaptor, callback = make_visualization_adaptor_from(args)

    with adaptor:
        sim = Simulation(iterations=args.timesteps)
        sim.run(callback)
